fix: skip the header length check and configure header length
opensource-nepal/commitlint pull request #68
Opened 2024-12-04 10:40 UTC by golesuman

## Description

Allow the  users to make the header length configurable and also allow disable header length check using a flag.

Introduced two flags

`--max-header-length`
`--disable-header-length-check`

## Related Issue

Fixes #67 

## Type of Change

Please mark the appropriate option below to describe the type of change your pull request introduces:

-   [x] Bug fix
-   [ ] New feature
-   [x] Enhancement
-   [ ] Documentation update
-   [ ] Refactor
-   [ ] Other (please specify)

## Checklist

-   [x] My pull request has a clear title and description.
-   [x] I have used [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
        Examples: `"fix: Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
-   [ ] I have added/updated the necessary documentation on `README.md`.
-   [ ] I have added appropriate test cases (if applicable) to ensure the changes are functioning correctly.

## Additional Notes

There is one issue with HEADER_LENGTH_ERROR be cause of COMMIT_HEADER_MAX_LENGTH constant. 

I tried to set "%s" in the message but it seems to fail the tests because of fixers LINTER_FIXTURE_PARAMS and we need some way to pass the value to this fixture .

By submitting this pull request, I confirm that I have read and complied with the contribution guidelines of this project.

2024-12-17 17:02 UTC, aj3sh commented
Hi @golesuman, Thanks for your contribution. Any updates on this PR? I haven't reviewed the PR since it's in the draft.

2024-12-18 10:48 UTC, golesuman commented
> Hi @golesuman, Thanks for your contribution. Any updates on this PR? I haven't reviewed the PR since it's in the draft.

Hi @aj3sh. Could you review if the approach is okay ? It looks kinda hacky to be honest. I couldn't update fixtures to actually test the dynamic max_length as I mentioned above in the additional notes because of my schedule. If it looks good then we can actually do something about the test part :)

2024-12-20 13:48 UTC, aj3sh requested changes
I have reviewed the current changes and will look into the issue regarding the header length error.

Additionally, if the header length check is not disabled by default, the issue will remain unresolved since no changes have been made to the GitHub Actions. Therefore, I suggest disabling the header length check by default. The changes to GitHub Actions can be addressed later in this case.

2024-12-20 13:48 UTC, aj3sh commented on src/commitlint/cli.py
> +    output_group.add_argument(
issue: `output_group` is for verbose and quiet only.

2024-12-20 13:48 UTC, aj3sh commented on src/commitlint/cli.py
> +    if args.max_header_length and args.disable_header_length_check:
issue: these can be achieved through argsparse groups.

2024-12-20 13:48 UTC, aj3sh commented on src/commitlint/linter/_linter.py
> +                **{"max_header_length": max_header_length},  # type: ignore
suggestion: This will work too.
```suggestion
                max_header_length=max_header_length,
```

2024-12-20 13:48 UTC, aj3sh commented on src/commitlint/linter/validators.py
> +    @property
`@property` fits perfectly here.

2024-12-20 13:48 UTC, aj3sh commented on src/commitlint/linter/_linter.py
> -    return run_validators(
suggestion: I never thought the task was going to be this tough. I have a few alternative suggestions that are effective and require fewer code changes.

However, our tool has a config for storing such configurations. It's already been implemented for verbose and quiet options, you can check that. With that said, the changes will only be on `HeaderLengthValidator` where the actual validator runs.

2025-02-11 14:02 UTC, closed without merging